"""gogo

Revision ID: 208b00cd327f
Revises: 33642f1ffecb
Create Date: 2021-11-24 15:55:27.486740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208b00cd327f'
down_revision = '33642f1ffecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_fund', sa.Column('date_of_price', sa.DateTime(), nullable=True))
    op.add_column('investment_fund', sa.Column('daily_change', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_fund', 'daily_change')
    op.drop_column('investment_fund', 'date_of_price')
    # ### end Alembic commands ###
