"""funds table added

Revision ID: 4a5f18590aad
Revises: 7703a899580c
Create Date: 2021-10-22 13:59:08.413985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5f18590aad'
down_revision = '7703a899580c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundname', sa.String(length=200), nullable=False),
    sa.Column('fundabbrv', sa.String(length=10), nullable=False),
    sa.Column('portfolio', sa.String(length=30), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundabbrv')
    )
    op.create_unique_constraint(None, 'clients', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_table('investment_fund')
    # ### end Alembic commands ###
