"""Added d Foreign Key

Revision ID: ccd6a412b1f6
Revises: 4a5f18590aad
Create Date: 2021-10-31 17:04:16.952817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccd6a412b1f6'
down_revision = '4a5f18590aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['investment_fund.id'], ),
    sa.PrimaryKeyConstraint('fund_id', 'client_id')
    )
    op.create_unique_constraint(None, 'clients', ['username'])
    op.drop_column('clients', 'prefs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('prefs', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_table('preferences')
    # ### end Alembic commands ###
